### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by whale2002** [yangchen0625/supermall#1]
我目前会一些Vue基本语法，还没有接触vue脚手架。刚开始很新鲜，现在有点枯燥了。想请问您是怎么学习Vue的呢，有推荐的资料吗

**Comment by yangchen0625** [comment]
> 我目前会一些Vue基本语法，还没有接触vue脚手架。刚开始很新鲜，现在有点枯燥了。想请问您是怎么学习Vue的呢，有推荐的资料吗

        我是在B站上看的Vue学习视频，名字叫《2019年最全最新Vue、Vuejs教程，从入门到精通》，这个项目我也是按照这个视频里一步步在做。其实吧，你想做任何事，学任何东西，都最好有一个目标，或者是想完成某些事。
        Vue这个框架我也只学了两个月左右。我现在是大四，去年秋招找实习岗位嘛，当时应聘的是java岗位，不过也是个中小型公司，这种公司进去的话前后端都要做。当时一进去就让你接触Vue或者React和SpringBoot，我那时还没接触过前端框架，基础语法都不懂，所以就是硬着头皮做，还好是二次迭代开发，可以借鉴其他别人写好的模块去做，也算是做完了，不过到过年放假的时候辞职了。因为自身确实难以胜任这种工作强度，每天干到深夜，身体吃不消，并且技术不足，做起来有些吃力，所以离职了。
       然后寒假的时候我就在家补课Vue嘛，也是为了做毕业设计，因为我毕设打算用Vue做。而且在前端面试时，会一种前端框架对自己有很大的加分，如果你只会什么js，css的话竞争力太小了。
       我的建议是， 边看视频的同时要边写，一定要写，不写就没有意思。并且有一个目标，为了做毕设，某些作业项目，或者为了今后工作。你现在应该是大学生吧，越早接触框架对自己越有好处。

**Comment by whale2002** [comment]
昨天用邮箱回复的您，不知道您收到没有，再次表达感谢。
